version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    target-branch: "gh-pages"
    schedule:
      interval: daily
