apiVersion: v1
kind: ConfigMap
metadata:
  name: cpusets-configmaps
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- with .Values.configMapData }}
    {{- toYaml . | nindent 2 }}
  {{- end }}