{{- if .Values.deviceplugin.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeservice-cpupools-controller.deviceplugin.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubeservice-cpupools-controller.labels" . | nindent 4 }}
  {{- with .Values.deviceplugin.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}