{{- if .Values.installCRDs }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cosignkeys.kubeservice.cn
spec:
  group: kubeservice.cn
  names:
    kind: CosignKey
    listKind: CosignKeyList
    plural: cosignkeys
    singular: cosignkey
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: CosignKey is the Schema for the cosignkeys API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CosignKeySpec defines the desired state of CosignKey
            properties:
              authorities:
                description: Foo is an example field of CosignKey. Edit CosignKey_types.go
                  to remove/update
                properties:
                  key:
                    items:
                      type: string
                    type: array
                required:
                - key
                type: object
            required:
            - authorities
            type: object
          status:
            description: CosignKeyStatus defines the observed state of CosignKey
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: cosignkeys
    singular: cosignkey
    kind: CosignKey
    listKind: CosignKeyList
    shortNames:
    - ck
{{- end }}