apiVersion: v2
appVersion: 1.1.1
description: Prometheus Pingmesh Exporter
home: https://github.com/kubeservice-stack/pingmesh-agent
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
keywords:
- prometheus
- pimgmesh
- monitoring
maintainers:
- email: dongjiang1989@126.com
  name: dongjiang
name: prometheus-pingmesh-exporter
sources:
- https://github.com/kubeservice-stack/pingmesh-agent
type: application
version: 1.1.1
annotations:
  artifacthub.io/signKey: |
    fingerprint: 54145DF6791F044DDB2C9219F42BCA7408363131
    url: https://kubeservice-stack.github.io/kubservice-charts/pgp_keys.asc
  artifacthub.io/maintainers: |
    - name: dongjiang
      email: dongjiang1989@126.com
