apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-pods-webhook-configuration
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: mutating-pods-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kubeservice-custom-limitrange.fullname" . }}-certificate
webhooks:
  - name: mutating-pods-{{ include "kubeservice-custom-limitrange.fullname" . }}-svc.{{ .Release.Namespace }}.svc
    clientConfig:
      service:
        name: {{ include "kubeservice-custom-limitrange.fullname" . }}-svc
        namespace: {{ .Release.Namespace | quote }}
        path: "/mutate"
        port: 443
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    admissionReviewVersions: ["v1","v1beta1"]
    sideEffects: None
    timeoutSeconds: 15
    failurePolicy: Ignore
