kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubeservice-custom-limitrange.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- include "kubeservice-custom-limitrange.annotations" . | nindent 4 }}
rules:
- apiGroups: ["custom.cmss.com"]
  resources: ["customlimitranges"]
  verbs: ["get"]
