apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeservice-custom-limitrange.fullname" . }}-svc
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubeservice-custom-limitrange.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "kubeservice-custom-limitrange.selectorLabels" . | nindent 4 }}