apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: '{{ include "kubeservice-lxcfs-webhook.fullname" . }}-certificate'
  namespace: {{ .Release.Namespace | quote }}
spec:
  dnsNames:
  - '{{ include "kubeservice-lxcfs-webhook.fullname" . }}-svc.{{ .Release.Namespace | quote }}.svc'
  - '{{ include "kubeservice-lxcfs-webhook.fullname" . }}-svc.{{ .Release.Namespace | quote }}.svc.cluster.local'
  - 'mutating-{{ include "kubeservice-lxcfs-webhook.fullname" . }}-svc.{{ .Release.Namespace | quote }}.svc'
  - 'validation-{{ include "kubeservice-lxcfs-webhook.fullname" . }}-svc.{{ .Release.Namespace | quote }}.svc'
  - 'mutating-{{ include "kubeservice-lxcfs-webhook.fullname" . }}-svc.{{ .Release.Namespace | quote }}.svc.cluster.local'
  - 'validation-{{ include "kubeservice-lxcfs-webhook.fullname" . }}-svc.{{ .Release.Namespace | quote }}.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: '{{ include "kubeservice-lxcfs-webhook.fullname" . }}-selfsigned-issuer'
  secretName: '{{ include "kubeservice-lxcfs-webhook.fullname" . }}-certificate'