kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubeservice-lxcfs-webhook.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubeservice-lxcfs-webhook.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ include "kubeservice-lxcfs-webhook.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io