kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubeservice-cosign-webhook.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubeservice-cosign-webhook.serviceAccountName" . }}
  namespace: cosign
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ include "kubeservice-cosign-webhook.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io