kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubeservice-cosign-webhook.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
rules:
- apiGroups: ["kubeservice.cn"]
  resources: ["cosignkeys", "cosignkeys/*"]
  verbs: ["*"]