apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeservice-namespace-node-affinity.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- toYaml .Values.securityContext | nindent 2}}