kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubeservice-namespace-node-affinity.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
